# Generated by Django 2.0.5 on 2018-08-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='something_1',
        ),
    ]
